// <auto-generated />
using System;
using Akshaya.Modules.Identity.Infrastructure.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Akshaya.Api.Infrastructure.Migrations;

[DbContext(typeof(IdentityDbContext))]
[Migration("20260902224435_InitialIdentity")]
partial class InitialIdentity
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("identity")
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Akshaya.Modules.Identity.Infrastructure.Ef.SavedCredentialRow", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<string>("ConnectorId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("KeyId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTimeOffset?>("LastUsedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Nickname")
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.Property<byte[]>("Payload")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.Property<string>("RememberedKeys")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("UserId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<byte[]>("WrappedDataKey")
                    .IsRequired()
                    .HasColumnType("bytea");

                b.HasKey("Id");

                b.HasIndex("UserId", "ConnectorId");

                b.ToTable("saved_broker_credentials", "identity");
            });

        modelBuilder.Entity("Akshaya.Modules.Identity.Infrastructure.Ef.UserAccountRow", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("DisplayName")
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("character varying(320)");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<DateTimeOffset?>("LastSignedInAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("NormalisedEmail")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("character varying(320)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(512)
                    .HasColumnType("character varying(512)");

                b.Property<string>("TenantId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.HasKey("Id");

                b.HasIndex("NormalisedEmail")
                    .IsUnique();

                b.ToTable("users", "identity");
            });

        modelBuilder.Entity("Akshaya.Modules.Identity.Infrastructure.Ef.SavedCredentialRow", b =>
            {
                b.HasOne("Akshaya.Modules.Identity.Infrastructure.Ef.UserAccountRow", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
